---
# tasks file for testsrv-role

- name: create group for {{ service_name }}
  group:
    name: "{{ group_name }}"
    state: present

- name: create user for {{ service_name }}
  user:
    name: "{{ user_name }}"
    create_home: yes
    group: "{{ group_name }}"
    state: present

- name: get {{ service_name }} binary
  get_url:
    dest: "/home/{{ user_name }}"
    url: "https://github.com/imorph/{{ service_name }}/releases/download/{{ version }}/{{ service_name }}-{{ version }}-linux-amd64.tar.gz"

- name: unpack {{ service_name }} binary
  unarchive: 
    src: "/home/{{ user_name }}/{{ service_name }}-{{ version }}-linux-amd64.tar.gz"
    dest: "/home/{{ user_name }}" 
    remote_src: true

- name: deploy {{ service_name }} systemd unit file
  template:
    src: "templates/testsrv.service"
    dest: "/usr/lib/systemd/system/{{ service_name }}.service"

- name: enable and start {{ service_name }}
  systemd:
    name: "{{ service_name }}"
    enabled: true
    daemon_reload: yes
    state: started
